description = "TODAY Service Provider"


dependencies {

  api project(":today-remoting")
  api project(":today-cloud-core")
  api project(":today-service-api")

  optional 'cn.taketoday:infra-context'
  optional project(":today-remoting-transport-tcp")

  annotationProcessor 'cn.taketoday:infra-configuration-processor'
}

// --add-opens=java.base/java.nio=ALL-UNNAMED
//--add-opens=java.base/sun.nio.ch=ALL-UNNAMED