description = 'TODAY Cloud Dependencies'

apply plugin: 'java-platform'
apply from: "$rootDir/gradle/publications.gradle"

javaPlatform {
  allowDependencies()
}

def infraVersion() {
  Properties properties = new Properties()
  file("$rootDir/buildSrc/gradle.properties").withReader {
    properties.load(it)
  }
  return properties['infraVersion']
}

dependencies {
  var version = infraVersion()

  api(platform("cn.taketoday:infra-bom:$version"))
  api platform('io.micrometer:micrometer-tracing-bom:1.5.2')

  api(platform(project(":today-cloud-bom")))

  constraints {

  }
}

publishing {
  publications {
    maven(MavenPublication) {
      from components.javaPlatform
    }
  }
}


apply from: "$rootDir/gradle/signing.gradle"
