description = "TODAY Service Client"


dependencies {
  api project(":today-remoting")
  api project(":today-cloud-core")
  api project(":today-service-api")
  api project(":today-service-discovery")

  optional "cn.taketoday:infra-context"
  optional project(":today-remoting-transport-tcp")

  testImplementation "cn.taketoday:infra-app-test"
//  testImplementation project(":today-cloud-samples:demo-tests:demo-user-api")

}