apply plugin: "signing"
apply plugin: "maven-publish"

publishing.publications.withType(MavenPublication.class) {
  pom {
    afterEvaluate {
      name = project.name
      description = project.description
    }
    url = "https://github.com/today-tech/today-cloud"
    organization {
      name = "TODAY Tech"
      url = "https://taketoday.cn"
    }
    licenses {
      license {
        name = 'The Apache License, Version 2.0'
        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
        distribution = "repo"
      }
    }
    scm {
      url = "https://github.com/today-tech/today-cloud.git"
      connection = "scm:git:git://github.com/today-tech/today-cloud"
      developerConnection = "scm:git:git://github.com/today-tech/today-cloud"
    }
    developers {
      developer {
        id = "taketoday"
        name = "Harry Yang"
        email = "taketoday@foxmail.com"
      }
    }
    issueManagement {
      system = "GitHub"
      url = "https://github.com/today-tech/today-cloud/issues"
    }
  }
  versionMapping {
    usage('java-api') {
      fromResolutionResult()
    }
    usage('java-runtime') {
      fromResolutionResult()
    }
  }
}