description = "Demo Client"


dependencies {
  implementation project(":today-service-client")
  implementation project(":today-cloud-samples:demo-tests:demo-user-api")

  implementation 'cn.taketoday:infra-starter-web'
  implementation 'cn.taketoday:infra-starter-json'
  implementation 'cn.taketoday:infra-starter-netty-server'
  implementation 'ch.qos.logback:logback-classic'

  implementation "com.google.protobuf:protobuf-java"

  implementation project(":today-service-registry-simple-discovery")

}