service:
  provider:
    uri: '/provider'

registry:
  http-url: 'http://localhost:5000/services'

  services:
    uri: '/services'

infra:
  profiles:
    active: dev

logging:
  level:
    cn.taketoday.cloud.protocol: debug

server:
  netty:
    shutdown:
      quiet-period: 0
      unit: seconds
      timeout: 2
