
infra:
  profiles:
    active: dev

  cloud:
    service-registry:
      uri: http://localhost:5000

logging:
  level:
    root: info
    web: trace
    cn.taketoday.demo: debug
    infra.cloud.protocol: debug


server:
  netty:
    shutdown:
      quiet-period: 0
      unit: seconds
      timeout: 2
