description = "Demo Service Registry"

apply plugin: "java"
apply plugin: "infra.application"

//infraJar {
//  enabled = false
//}

dependencies {
  implementation project(":today-service-registry-simple-server")

  implementation 'cn.taketoday:infra-starter-web'
  implementation 'cn.taketoday:infra-starter-netty-server'
  implementation 'cn.taketoday:infra-starter-application'
  implementation 'ch.qos.logback:logback-classic'

  annotationProcessor 'cn.taketoday:infra-configuration-processor'
}
