server:
  port: 5000

#registry:
#  services:
#    uri: '/services'

web:
  resources:
    add-default-mappings: false

infra:
  profiles:
    active: dev

configq:
  server:
    etcd:
      endpoints: "http://localhost:2379"
      username: "root"
      password: "88888888"
      namespace: ${app.name}/

app:
  name: demo
