server:
  port: 9000

web:
  resources:
    add-default-mappings: false
  error:
    include-message: always

infra:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false


config:
  server:
    etcd:
      endpoints: "http://localhost:2379"
      username: "root"
      password: "88888888"
      namespace: ${app.name}/

app:
  name: demo

logging:
  level:
    root: info
    web: trace