
infra:
  profiles:
    active: dev
  cloud:
    service-registry:
      auto-registration:
        fail-fast: true

      simple:
        instance-port: 9000
      uri: http://localhost:5000

service:
  server:
    port: 9000

logging:
  level:
    root: info
    web: trace
    cn.taketoday.demo: debug
    infra.cloud.provider: debug