infra:
  profiles:
    active: dev


today:
  service:
    auto-registration:
      fail-fast: true
    server:
      port: 8081

  service-registry:
    simple:
      uri: http://localhost:9000

logging:
  level:
    root: info
    web: trace
    cn.taketoday.demo: debug
    infra.cloud.provider: debug