server:
  port: 9000

web:
  resources:
    add-default-mappings: false

infra:
  profiles:
    active: dev
  cloud:
    service-registry:
      auto-registration:
        port: 9000
        fail-fast: true

logging:
  level:
    root: info
    web: trace
    cn.taketoday.demo: debug
    infra.cloud.provider: debug